spring:
    application:
        name: client      
    server:
        port: 8099
    eureka: 
        client: 
            serviceUrl: 
                defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
            instance:
                preferIpAddress: true